### PR TITLE
docs: add `OpenAPITool` notebook

### PR DESCRIPTION
**Pull request by anakin87**
### Proposed Changes:

Add a notebook with usage examples for the `OpenAPITool`

### Notes for the reviewer
Works with https://github.com/deepset-ai/haystack-experimental/commit/54a478c7c4886d3127ceed6481ecdc0277301da9.
Can be merged once a new version of the `haystack-experimental` package is released.

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.
- I documented my code
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and fixed any issue

### CODE REVIEW

**Comment by vblagoje** [comment]
Looks good @shadeMe @anakin87 I would perhaps just omit any `generator_api_params={"model":"gpt-3.5-turbo"},` to make things simpler. User can discover these themselves. Not hard pressed on this, just a suggestion.

**Review by vblagoje — APPROVED** [review]
🚀

**Review by shadeMe — APPROVED** [review]

**Comment by anakin87** [comment]
@TuanaCelik can you take a look?

@shadeMe this works with main. Should I wait for a new package release before merging?

**Comment by shadeMe** [comment]
> @shadeMe this works with main. Should I wait for a new package release before merging?

No need - Feel free to merge.

**Review by TuanaCelik — APPROVED** [review]
Lgtm, but I have one question:
What's the behaviuor you change
```
result = pipe.run(data={"meteo": {"messages": [ChatMessage.from_user("weather in San Francisco, US")]},
                        "prompt_adapter": {"user_message": [ChatMessage.from_user("Explain the weather in San Francisco in a human understandable way")]}})
```

to something that doesn't have to indicate San Francisco or the exact copy of the user message to the tool? And similarly, what is the behaviour if the uesr question to the tool is like "What's the weather in San Francisco?"

**Comment by anakin87** [comment]
@TuanaCelik it more or less works.

`pipe.run(data={"meteo": {"messages": [ChatMessage.from_user("weather in San Francisco")]},
                        "prompt_adapter": {"user_message": [ChatMessage.from_user("What's the weather?")]}})`

> The current weather in the location provided (latitude: 37.763283, longitude: -122.41286) is as follows:

> - Temperature: 12.1°C
> - Windspeed: 7.2 km/h
> - Wind direction: 264°
> - Time: 2024-07-26T11:00
> - Weather code: 0
> 
> It seems to be a bit chilly with moderate winds blowing from the west.

**Pull request merged**
