### PR TITLE
feat: Add notebook for RAG eval harness

### PR DESCRIPTION
**Pull request by shadeMe**
### Proposed Changes:

 
 
Add a notebook to showcase the RAG evaluation harness.

### Notes for the reviewer

Depends on the following: https://github.com/deepset-ai/haystack/pull/7818

Without the above PR, the execution of the harness will break since it attempts to serialize the evaluation pipeline. To test it locally, either pull the above PR and build `haystack-ai` locally or remove the answer faithfulness metric from the harness.

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.txt)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.
- I documented my code
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and fixed any issue

### CODE REVIEW

**Comment by TuanaCelik** [comment]
PSA, you can view the notebook here: https://colab.research.google.com/github/shadeMe/haystack-experimental/blob/feat/rag-eval-harness-notebook/examples/rag_eval_harness.ipynb

**Comment by davidsbatista** [comment]
I think the code is already there, and it shows how to use it. Nevertheless, this notebook needs some improvement regarding "documentation" and the code's organisation. Here are my comments:

- Create an intro section shortly describing what the notebook is about
Do not assume anything is installed; explicitly state what dependencies are needed and the commands to install them. (I think you have most of it already there.)
- Add textual descriptions/instructions to each section/snippet (i.e.: dataset prep., indexing, retrieval, eval., results analysis), instead of just the title
- Make sure to have any relevant links to Documentation and/or blog posts related to the snippets/sections if needed
- Move the imports to their related sections/snippets of code instead of having everything at the beginning
- See some of the tutorials here for guidance: https://github.com/deepset-ai/haystack-tutorials?tab=readme-ov-file
- One example: https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/39_Embedding_Metadata_for_Improved_Retrieval.ipynb

**Comment by davidsbatista** [comment]
just noticed that the `keyword_eval_harness` is not used anywhere

**Comment by davidsbatista** [comment]
> PSA, you can view the notebook here: https://colab.research.google.com/github/shadeMe/haystack-experimental/blob/feat/rag-eval-harness-notebook/examples/rag_eval_harness.ipynb

@TuanaCelik, did you manage to run this collab/notebook?

**Comment by davidsbatista** [comment]
@shadeMe can you open another PR only with the `pytoml` ?

**Review by bilgeyucel — APPROVED** [review]

**Pull request merged**
