### PR TITLE
chore:Format change in Anthropic response

### PR DESCRIPTION
**Pull request by vblagoje**
Update to the latest Anthropic usage format i.e. more specifically `MessageStartEvent` changed a bit to include more usage token fields

### CODE REVIEW

**Comment by vblagoje** [comment]
@anakin87 please have a look, seems like an update in Anthropic lib

**Comment by anakin87** [comment]
I tried to fix that in https://github.com/deepset-ai/haystack-core-integrations/pull/1252

**Comment by vblagoje** [comment]
Deal @anakin87 let's release new Anthropic, I'll close this one

**Comment by vblagoje** [comment]
@anakin87 this is still needed even with the new anthropic-haystack that you just released.

**Review by anakin87 — APPROVED** [review]
Thanks!

**Pull request merged**
